# Generated by Django 5.0.2 on 2024-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=70)),
                ('stuid', models.IntegerField(max_length=10)),
                ('stupass', models.CharField(max_length=50)),
            ],
        ),
    ]
