# Generated by Django 5.0.2 on 2024-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stuid',
            field=models.IntegerField(),
        ),
    ]
